-- Sri Kangna CRM: Jewellery on Rent bookings
-- Run once in Supabase → SQL Editor → New query → paste → Run. Safe to run again.

create table if not exists public.rentals (
  id uuid primary key default gen_random_uuid(),
  booking_no bigint generated by default as identity,   -- shown as R-001, R-002 ...
  book_date date not null default current_date,         -- date of booking
  booked_for text,                                       -- occasion: Wedding, Engagement ...
  name text not null,
  address text,
  mob1 text,
  mob2 text,
  set_code text not null,
  colour text,
  dod date not null,                                     -- date of delivery
  dod_time time,
  dor date not null,                                     -- date of return
  dor_time time,
  rate numeric not null default 0,
  advance numeric not null default 0,
  security numeric not null default 0,
  note text,
  status text not null default 'booked',                 -- booked | delivered | returned | cancelled
  delivered_at timestamptz,
  returned_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists rentals_dod_idx on public.rentals (dod);
create index if not exists rentals_dor_idx on public.rentals (dor);

alter table public.rentals enable row level security;
drop policy if exists "Signed-in users manage rentals" on public.rentals;
create policy "Signed-in users manage rentals" on public.rentals
  for all to authenticated using (true) with check (true);
